# docker-compose.yml
version: '2'
services:
    prometheus:
        image: prom/prometheus:v2.11.1
        volumes:
            - prometheus_data:/prometheus
            - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./docker/prometheus/aerospike_rules.yml:/etc/prometheus/aerospike_rules.yml
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        ports:
            - '9090:9090'

    alertmanager:
        image: prom/alertmanager
        volumes:
            - alertmanager_data:/alertmanager
            - ./docker/prometheus/alertmanager.yml:/etc/prometheus/alertmanager.yml
        command:
            - '--config.file=/etc/prometheus/alertmanager.yml'
            - '--storage.path=/alertmanager'
        ports:
            - 9093:9093

#    node-exporter:
#        image: prom/node-exporter:v0.18.1
#        ports:
#            - '9100:9100'

    grafana:
            image: grafana/grafana:6.3.2
            volumes:
                - grafana_data:/var/lib/grafana
                - ./docker/grafana/plugins:/grafana_plugins
                - ./docker/grafana/dashboards/:/var/lib/grafana/dashboards/
                - ./docker/grafana/provisioning/:/etc/grafana/provisioning/
                # - ./docker/grafana/provisioning/dashboards/all.yaml:/etc/grafana/provisioning/dashboards/all.yaml
                # - ./docker/grafana/provisioning/datasources/all.yaml:/etc/grafana/provisioning/datasources/all.yaml
                # - ./docker/grafana/dashboards/cluster.json:/var/lib/grafana/dashboards/cluster.json
                # - ./docker/grafana/dashboards/node.json:/var/lib/grafana/dashboards/node.json
                # - ./docker/grafana/dashboards/namespace.json:/var/lib/grafana/dashboards/namespace.json
                # - ./docker/grafana/dashboards/latency.json:/var/lib/grafana/dashboards/latency.json
                # - ./docker/grafana/dashboards/alerts.json:/var/lib/grafana/dashboards/alerts.json
            environment:
                - GF_SECURITY_ADMIN_PASSWORD=pass
                - GF_PATHS_PLUGINS=/grafana_plugins
            depends_on:
                - prometheus
            ports:
                - "3000:3000"
volumes:
        prometheus_data: {}
        alertmanager_data: {}
        grafana_data: {}
        grafana_plugins: {}
