# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
  - "/etc/prometheus/aerospike_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'aerospike'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
#        - targets: ['192.168.106.57:9145', '192.168.106.57:9146', '192.168.106.57:9147', '192.168.106.57:9150', '192.168.106.57:8150', '192.168.106.57:9149', '192.168.106.57:9148', '192.168.106.57:9147', '192.168.106.57:9146', '192.168.106.57:9145']

    static_configs:
        - targets: ['192.168.106.96:49152','192.168.106.96:49153','192.168.106.96:49154','192.168.106.96:49155','192.168.106.96:49156','192.168.106.96:49157','192.168.106.96:49158','192.168.106.96:49159','192.168.106.96:49160']
